name: CI/CD Pipeline for Project SYNK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.13.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.0  # Replace with your desired Node.js version

      - name: Install dependencies
        run: yarn # Or yarn install, if you use Yarn

      - name: Build Electron app
        run: yarn electron:build  # Replace with your build command (e.g., electron-builder)

      # Add a testing step here if you have tests (optional)
