# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-mac:
    runs-on: macos-latest

    permissions:
      contents: read
      packages: write 

    strategy:
      matrix:
        node-version: [18.2.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      uses: actions/setup-node@v3
      
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn
    - run: cd Frontend && yarn
    - run: cd Backend && yarn
    - run: yarn upgrade
    - run: yarn electron:build
    - run: npm test
